/* RDR: raw-data weather renderer. External services provide numbers/vectors, never finished map images. */
const CFG={
  width:456,height:257,header:22,footer:19,mapTop:22,mapBottom:238,mapHeight:216,
  home:{lat:26.06197904865014,lon:-80.18787062578414},
  refreshMs:120000,frameMs:700,
  views:[
    {id:'home',name:'HOME',duration:12000,bbox:[-80.48,25.82,-79.92,26.31],radar:[['CONUS','BREF_QCD']],labels:[['HOME',26.06198,-80.18787],['FT LAUDERDALE',26.1224,-80.1373],['HOLLYWOOD',26.0112,-80.1495],['DAVIE',26.0765,-80.2521],['MIRAMAR',25.9861,-80.3036]]},
    {id:'metro',name:'BROWARD / MIAMI',duration:11000,bbox:[-81.08,25.20,-79.65,26.95],radar:[['CONUS','BREF_QCD']],labels:[['FT LAUDERDALE',26.1224,-80.1373],['MIAMI',25.7617,-80.1918],['WEST PALM',26.7153,-80.0534],['HOMESTEAD',25.4687,-80.4776],['KEY LARGO',25.0865,-80.4473]]},
    {id:'florida',name:'FLORIDA',duration:10000,bbox:[-87.8,24.0,-79.3,31.25],radar:[['CONUS','CREF_QCD']],labels:[['MIAMI',25.7617,-80.1918],['KEY WEST',24.5551,-81.78],['NAPLES',26.1423,-81.7948],['TAMPA',27.9506,-82.4572],['ORLANDO',28.5383,-81.3792],['JACKSONVILLE',30.3322,-81.6557]]},
    {id:'regional',name:'GULF / CUBA',duration:12000,bbox:[-98.0,18.0,-72.0,32.8],radar:[['CONUS','CREF_QCD'],['CARIB','CREF_QCD']],labels:[['FLORIDA',27.4,-81.7],['CUBA',22.2,-79.7],['HAVANA',23.1136,-82.3666],['BAHAMAS',24.3,-76.7],['YUCATAN',20.8,-87.1],['GULF OF MEXICO',25.6,-90.0]]}
  ],
  mrms:'https://mrms.ncep.noaa.gov/RIDGEII/L2',
  warnings:'https://mapservices.weather.noaa.gov/eventdriven/rest/services/WWA/watch_warn_adv/MapServer/0/query',
  reference:'https://mapservices.weather.noaa.gov/static/rest/services/nws_reference_maps/nws_reference_map/MapServer',
  tropics:'https://mapservices.weather.noaa.gov/tropical/rest/services/tropical/NHC_tropical_weather_summary/MapServer',
  nws:'https://api.weather.gov'
};

const panel=document.getElementById('panel'),canvas=document.getElementById('display'),ctx=canvas.getContext('2d',{alpha:false}),boot=document.getElementById('boot');
const q=new URLSearchParams(location.search),forced=q.get('view');
const state={current:0,frames:new Map(),frame:0,bounds:new Map(),warnings:[],states:[],counties:[],tropics:[],weather:null,home:{dbz:null,status:'...',nearest:null},motion:null,lastRadar:null,errors:[],rotation:null,anim:null};

function fit(){const s=Math.min(innerWidth/CFG.width,innerHeight/CFG.height);panel.style.transform=`scale(${Math.max(.2,s)})`}
function view(){return CFG.views[state.current]}
function xy(lat,lon,b=view().bbox){const [w,s,e,n]=b;return{x:(lon-w)/(e-w)*CFG.width,y:CFG.mapTop+(n-lat)/(n-s)*CFG.mapHeight}}
function ll(x,y,b=view().bbox){const [w,s,e,n]=b;return{lon:w+x/CFG.width*(e-w),lat:n-(y-CFG.mapTop)/CFG.mapHeight*(n-s)}}
function within(lat,lon,b=view().bbox){return lon>=b[0]&&lon<=b[2]&&lat>=b[1]&&lat<=b[3]}
function safe(v,d=''){return v==null?d:String(v)}
async function getText(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'text/plain,*/*'}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.text()}
async function getJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/geo+json,application/json','User-Agent':'RDR-Yodeck'}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
function parseRadarTime(name){const m=name.match(/_(\d{8})_(\d{6})\.tif\.gz$/);if(!m)return null;return new Date(`${m[1].slice(0,4)}-${m[1].slice(4,6)}-${m[1].slice(6,8)}T${m[2].slice(0,2)}:${m[2].slice(2,4)}:${m[2].slice(4,6)}Z`)}
async function latestFiles(domain,product,count=6){const base=`${CFG.mrms}/${domain}/${product}/`;const html=await getText(base);const rx=new RegExp(`${domain}_L2_${product}_\\d{8}_\\d{6}\\.tif\\.gz`,'g');const names=[...new Set(html.match(rx)||[])].sort();if(!names.length)throw new Error(`no ${domain} ${product} files`);return names.slice(-count).map(name=>({name,url:base+name,time:parseRadarTime(name)}))}
async function gunzip(ab){if('DecompressionStream'in self){const s=new Blob([ab]).stream().pipeThrough(new DecompressionStream('gzip'));return new Response(s).arrayBuffer()}return fflate.gunzipSync(new Uint8Array(ab)).buffer}
function rasterWindow(image,bbox){const ib=image.getBoundingBox(),iw=image.getWidth(),ih=image.getHeight();const x0=Math.max(0,Math.floor((bbox[0]-ib[0])/(ib[2]-ib[0])*iw));const x1=Math.min(iw,Math.ceil((bbox[2]-ib[0])/(ib[2]-ib[0])*iw));const y0=Math.max(0,Math.floor((ib[3]-bbox[3])/(ib[3]-ib[1])*ih));const y1=Math.min(ih,Math.ceil((ib[3]-bbox[1])/(ib[3]-ib[1])*ih));return[x0,y0,Math.max(x0+1,x1),Math.max(y0+1,y1)]}
async function decodeTiff(url,bbox,w=CFG.width,h=CFG.mapHeight){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} radar file`);const raw=await gunzip(await r.arrayBuffer());const t=await GeoTIFF.fromArrayBuffer(raw),image=await t.getImage(),window=rasterWindow(image,bbox);const rs=await image.readRasters({window,width:w,height:h,resampleMethod:'nearest'});return{data:rs[0],width:w,height:h,bbox:image.getBoundingBox(),nodata:image.getGDALNoData?.()}}
function dbzColor(v,a=230){if(!Number.isFinite(v)||v<5||v>95)return[0,0,0,0];if(v<10)return[20,95,115,a];if(v<15)return[25,140,125,a];if(v<20)return[20,175,85,a];if(v<25)return[35,205,55,a];if(v<30)return[105,225,45,a];if(v<35)return[200,230,35,a];if(v<40)return[255,210,30,a];if(v<45)return[255,155,25,a];if(v<50)return[255,90,25,a];if(v<55)return[240,40,35,a];if(v<60)return[205,35,100,a];if(v<65)return[180,40,180,a];if(v<70)return[150,55,220,a];return[235,235,255,a]}
function frameCanvas(data,w=CFG.width,h=CFG.mapHeight){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d'),im=x.createImageData(w,h);for(let i=0,j=0;i<data.length;i++,j+=4){const [r,g,b,a]=dbzColor(Number(data[i]));im.data[j]=r;im.data[j+1]=g;im.data[j+2]=b;im.data[j+3]=a}x.putImageData(im,0,0);return c}
async function loadRadar(def){const all=[];for(const [domain,product] of def.radar){try{const files=await latestFiles(domain,product,6);for(let i=0;i<files.length;i++){if(!all[i])all[i]={time:files[i].time,layers:[]};const d=await decodeTiff(files[i].url,def.bbox);all[i].layers.push({domain,data:d.data,canvas:frameCanvas(d.data)})}}catch(e){state.errors.push(`radar ${domain}: ${e.message}`)}}if(!all.length)throw new Error('raw radar unavailable');state.frames.set(def.id,all);state.lastRadar=all[all.length-1].time;panel.dataset.radar='raw-geotiff';if(def.id==='home'){const last=all[all.length-1].layers[0]?.data;if(last)deriveHome(last,def);if(all.length>1)state.motion=motion(all[all.length-2].layers[0]?.data,last,def)}}
function deriveHome(data,def){const p=xy(CFG.home.lat,CFG.home.lon,def.bbox),ix=Math.max(0,Math.min(CFG.width-1,Math.round(p.x))),iy=Math.max(0,Math.min(CFG.mapHeight-1,Math.round(p.y-CFG.mapTop))),v=Number(data[iy*CFG.width+ix]);state.home.dbz=Number.isFinite(v)?v:null;state.home.status=v>=50?'INTENSE':v>=35?'HEAVY':v>=20?'RAIN':v>=5?'SPRINKLE':'DRY';let best=null;for(let rad=3;rad<150&&!best;rad+=3){for(let d=0;d<360;d+=10){const x=Math.round(ix+Math.cos(d*Math.PI/180)*rad),y=Math.round(iy+Math.sin(d*Math.PI/180)*rad);if(x<0||y<0||x>=CFG.width||y>=CFG.mapHeight)continue;const z=Number(data[y*CFG.width+x]);if(z>=20){best={rad,deg:d};break}}}if(best){const kmPerX=(def.bbox[2]-def.bbox[0])*111.32*Math.cos(CFG.home.lat*Math.PI/180)/CFG.width,kmPerY=(def.bbox[3]-def.bbox[1])*111.32/CFG.mapHeight,dx=Math.cos(best.deg*Math.PI/180)*best.rad*kmPerX,dy=-Math.sin(best.deg*Math.PI/180)*best.rad*kmPerY,mi=Math.hypot(dx,dy)*.621371,bearing=(Math.atan2(dx,dy)*180/Math.PI+360)%360,dirs=['N','NE','E','SE','S','SW','W','NW'];state.home.nearest={mi,dir:dirs[Math.round(bearing/45)%8]}}else state.home.nearest=null}
function motion(a,b,def){if(!a||!b)return null;let best={score:Infinity,dx:0,dy:0};for(let dy=-10;dy<=10;dy+=2)for(let dx=-10;dx<=10;dx+=2){let score=0,n=0;for(let y=14;y<CFG.mapHeight-14;y+=6)for(let x=14;x<CFG.width-14;x+=6){const av=Number(a[y*CFG.width+x]),bx=x+dx,by=y+dy,bv=Number(b[by*CFG.width+bx]);if(av>=15||bv>=15){score+=Math.abs(Math.max(0,av)-Math.max(0,bv));n++}}if(n>20&&score/n<best.score)best={score:score/n,dx,dy}}const kmX=(def.bbox[2]-def.bbox[0])*111.32*Math.cos(CFG.home.lat*Math.PI/180)/CFG.width,kmY=(def.bbox[3]-def.bbox[1])*111.32/CFG.mapHeight,km=Math.hypot(best.dx*kmX,best.dy*kmY),mph=km*.621371*30,bearing=(Math.atan2(best.dx,-best.dy)*180/Math.PI+360)%360,dirs=['N','NE','E','SE','S','SW','W','NW'];return{mph,dir:dirs[Math.round(bearing/45)%8],dx:best.dx,dy:best.dy}}
function arcQuery(base,bbox,extra={}){const p=new URLSearchParams({where:'1=1',geometry:bbox.join(','),geometryType:'esriGeometryEnvelope',inSR:'4326',outSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'*',returnGeometry:'true',f:'geojson',...extra});return`${base}?${p}`}
async function loadVectors(def){const jobs=[];jobs.push(getJson(arcQuery(CFG.warnings,def.bbox)).then(j=>state.warnings=j.features||[]).catch(e=>state.errors.push(`warnings ${e.message}`)));const simp=def.id==='home'?'.0005':def.id==='metro'?'.002':'.01';jobs.push(getJson(arcQuery(`${CFG.reference}/3/query`,def.bbox,{maxAllowableOffset:simp})).then(j=>state.states=j.features||[]).catch(()=>{}));if(def.id==='home'||def.id==='metro')jobs.push(getJson(arcQuery(`${CFG.reference}/2/query`,def.bbox,{maxAllowableOffset:simp})).then(j=>state.counties=j.features||[]).catch(()=>{}));else state.counties=[];const layers=[3,5,6,7,8,10,11,15,16];state.tropics=[];for(const id of layers)jobs.push(getJson(arcQuery(`${CFG.tropics}/${id}/query`,def.bbox,{maxAllowableOffset:'.02'})).then(j=>{for(const f of j.features||[])state.tropics.push({...f,_layer:id})}).catch(()=>{}));await Promise.all(jobs)}
async function loadWeather(){try{const point=await getJson(`${CFG.nws}/points/${CFG.home.lat.toFixed(4)},${CFG.home.lon.toFixed(4)}`),u=point.properties?.forecastHourly;if(!u)return;const fc=await getJson(u),p=fc.properties?.periods?.[0];state.weather=p?{temp:p.temperature,unit:p.temperatureUnit,wind:p.windSpeed,dir:p.windDirection,text:p.shortForecast}:null}catch(e){state.errors.push(`weather ${e.message}`)}}
function drawGeometry(g,stroke,fill,width=1){if(!g)return;ctx.save();ctx.lineWidth=width;ctx.strokeStyle=stroke;ctx.fillStyle=fill||'transparent';const polys=g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:null,lines=g.type==='LineString'?[g.coordinates]:g.type==='MultiLineString'?g.coordinates:null,points=g.type==='Point'?[g.coordinates]:g.type==='MultiPoint'?g.coordinates:null;if(polys)for(const poly of polys){ctx.beginPath();for(const ring of poly){ring.forEach((c,i)=>{const p=xy(c[1],c[0]);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.closePath()}if(fill)ctx.fill('evenodd');ctx.stroke()}if(lines)for(const line of lines){ctx.beginPath();line.forEach((c,i)=>{const p=xy(c[1],c[0]);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.stroke()}if(points)for(const c of points){const p=xy(c[1],c[0]);ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);if(fill)ctx.fill();ctx.stroke()}ctx.restore()}
function warningStyle(f){const p=f.properties||{},ph=safe(p.phenom||p.event).toUpperCase(),sg=safe(p.sig).toUpperCase();if(ph==='TO'||/TORNADO/.test(ph))return['#ff46ff','rgba(255,40,255,.08)',2];if(ph==='SV'||/SEVERE/.test(ph))return['#ffe84a','rgba(255,220,50,.06)',1.7];if(ph==='FF'||/FLOOD/.test(ph))return['#41ff6b','rgba(60,255,100,.05)',1.5];return[sg==='W'?'#ff8755':'#83c8ff','rgba(255,255,255,.025)',1]}
function drawBase(){ctx.fillStyle='#031019';ctx.fillRect(0,CFG.mapTop,CFG.width,CFG.mapHeight);ctx.strokeStyle='rgba(86,128,151,.10)';ctx.lineWidth=.5;for(let x=0;x<CFG.width;x+=57){ctx.beginPath();ctx.moveTo(x,CFG.mapTop);ctx.lineTo(x,CFG.mapBottom);ctx.stroke()}for(let y=CFG.mapTop;y<CFG.mapBottom;y+=54){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(CFG.width,y);ctx.stroke()}for(const f of state.states)drawGeometry(f.geometry,'rgba(180,215,230,.38)',null,.8);for(const f of state.counties)drawGeometry(f.geometry,'rgba(150,185,205,.17)',null,.45)}
function drawRadar(){const fs=state.frames.get(view().id)||[],fr=fs[state.frame%Math.max(1,fs.length)];if(!fr)return;for(const l of fr.layers)ctx.drawImage(l.canvas,0,CFG.mapTop);}
function drawTropics(){for(const f of state.tropics){const id=f._layer;if(id===6||id===16)drawGeometry(f.geometry,'#7fe9ff',null,1.4);else if(id===5)drawGeometry(f.geometry,'#fff','#fff',1);else if(id===7||id===15)drawGeometry(f.geometry,'#ff5d65','rgba(255,70,80,.09)',1.2);else drawGeometry(f.geometry,'rgba(255,184,70,.8)','rgba(255,164,50,.035)',.9)}}
function drawWarnings(){for(const f of state.warnings){const [s,fill,w]=warningStyle(f);drawGeometry(f.geometry,s,fill,w)}}
function drawLabels(){ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='700 7px ui-monospace,SFMono-Regular,Menlo,monospace';for(const [name,lat,lon] of view().labels){if(!within(lat,lon))continue;const p=xy(lat,lon);ctx.lineWidth=3;ctx.strokeStyle='rgba(0,0,0,.85)';ctx.strokeText(name,p.x,p.y);ctx.fillStyle='rgba(235,247,255,.88)';ctx.fillText(name,p.x,p.y)}const h=xy(CFG.home.lat,CFG.home.lon);if(within(CFG.home.lat,CFG.home.lon)){ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(h.x,h.y,6,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#54dcff';ctx.beginPath();ctx.arc(h.x,h.y,2.3,0,Math.PI*2);ctx.fill()}ctx.restore()}
function topAlert(){if(!state.warnings.length)return'';const p=state.warnings[0].properties||{};return safe(p.prod_type||p.event||p.phenom,'ALERT').replace(/_/g,' ').toUpperCase()}
function fmtTime(d){return d&&Number.isFinite(d.getTime())?d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}).replace(' ',''): '--:--'}
function drawHUD(){ctx.fillStyle='rgba(1,6,10,.96)';ctx.fillRect(0,0,CFG.width,CFG.header);ctx.fillRect(0,CFG.mapBottom,CFG.width,CFG.footer);ctx.strokeStyle='rgba(255,255,255,.12)';ctx.beginPath();ctx.moveTo(0,CFG.header-.5);ctx.lineTo(CFG.width,CFG.header-.5);ctx.moveTo(0,CFG.mapBottom+.5);ctx.lineTo(CFG.width,CFG.mapBottom+.5);ctx.stroke();ctx.textBaseline='middle';ctx.font='900 8px ui-monospace,SFMono-Regular,Menlo,monospace';ctx.fillStyle='#57e6ff';ctx.textAlign='left';ctx.fillText(`RDR  ${view().name}`,6,11);const weather=state.weather?`${Math.round(state.weather.temp)}°${state.weather.unit} ${state.weather.wind} ${state.weather.dir}`:'';ctx.fillStyle='#d8e8f2';ctx.textAlign='right';ctx.fillText(weather,450,11);ctx.font='900 7px ui-monospace,SFMono-Regular,Menlo,monospace';ctx.textAlign='left';const near=state.home.nearest?` · RAIN ${Math.max(1,Math.round(state.home.nearest.mi))}MI ${state.home.nearest.dir}`:'';ctx.fillStyle=state.home.status==='DRY'?'#8cd1ff':state.home.status==='SPRINKLE'?'#61e98b':state.home.status==='RAIN'?'#ffe95d':state.home.status==='HEAVY'?'#ff9a45':'#ff5a76';ctx.fillText(`HOME ${state.home.status}${near}`,6,247);let right=`RAW MRMS ${fmtTime(state.lastRadar)}`;if(state.motion&&state.motion.mph>2)right=`MOVE ${state.motion.dir} ${Math.round(state.motion.mph)}MPH · ${fmtTime(state.lastRadar)}`;ctx.fillStyle='#e7f2f8';ctx.textAlign='right';ctx.fillText(right,450,247);const alert=topAlert();if(alert){ctx.font='950 7px ui-monospace,SFMono-Regular,Menlo,monospace';ctx.textAlign='center';ctx.fillStyle='#ffdf55';ctx.fillText(alert,228,31)}}
function render(){drawBase();drawRadar();drawTropics();drawWarnings();drawLabels();drawHUD()}
async function loadView(def){panel.dataset.view=def.id;state.warnings=[];state.states=[];state.counties=[];state.tropics=[];await Promise.all([loadRadar(def),loadVectors(def)]);state.frame=0;render();panel.dataset.ready='true';boot.classList.add('off')}
function startAnim(){clearInterval(state.anim);state.anim=setInterval(()=>{const fs=state.frames.get(view().id)||[];if(fs.length>1){state.frame=(state.frame+1)%fs.length;render()}},CFG.frameMs)}
async function show(i){state.current=i;try{await loadView(view())}catch(e){state.errors.push(e.message);panel.dataset.radar='error';render()}startAnim()}
function schedule(){clearTimeout(state.rotation);if(forced)return;state.rotation=setTimeout(async()=>{await show((state.current+1)%CFG.views.length);schedule()},view().duration)}
async function refresh(){try{await Promise.all([loadWeather(),loadView(view())])}finally{render()}}
async function init(){fit();addEventListener('resize',fit,{passive:true});if(forced){const i=CFG.views.findIndex(v=>v.id===forced);if(i>=0)state.current=i}await Promise.all([loadWeather(),loadView(view())]);startAnim();schedule();setInterval(refresh,CFG.refreshMs);window.__RDR__=state}
init();
