'use strict';

const broadcastRadarCache=new Map(),broadcastCloudCache=new Map(),broadcastCellCache=new Map();

function broadcastBase(){
  const ocean=ctx.createLinearGradient(0,0,0,CFG.height);ocean.addColorStop(0,'#07151e');ocean.addColorStop(.52,'#04121a');ocean.addColorStop(1,'#020b11');ctx.fillStyle=ocean;ctx.fillRect(0,0,CFG.width,CFG.height);
  const seaGlow=ctx.createRadialGradient(CFG.width*.55,CFG.height*.42,20,CFG.width*.55,CFG.height*.42,CFG.width*.72);seaGlow.addColorStop(0,'rgba(21,56,70,.15)');seaGlow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=seaGlow;ctx.fillRect(0,0,CFG.width,CFG.height);
  drawStaticLand();const b=state.boundaries.get(view().id);for(const f of b?.states||[])drawGeometry(f.geometry,'rgba(224,233,237,.60)','#1d292f',.88);for(const f of b?.counties||[])drawGeometry(f.geometry,'rgba(126,151,162,.24)',null,.42);
}

function broadcastRadarSurfaces(frame,id=view().id){
  if(!frame)return null;const key=`${frame.key}|${id}|broadcast6`;if(broadcastRadarCache.has(key))return broadcastRadarCache.get(key);const a=frame.views[id],sw=Math.ceil(CFG.width/2),sh=Math.ceil(CFG.mapHeight/2),soft=document.createElement('canvas'),detail=document.createElement('canvas');soft.width=sw;soft.height=sh;detail.width=CFG.width;detail.height=CFG.mapHeight;const sx=soft.getContext('2d'),dx=detail.getContext('2d'),si=sx.createImageData(sw,sh),di=dx.createImageData(CFG.width,CFG.mapHeight),sd=si.data,dd=di.data;
  for(let y=0;y<sh;y++)for(let x=0;x<sw;x++){const cx=x*2,cy=y*2;let sum=0,n=0,max=0;for(let yy=Math.max(0,cy-2);yy<=Math.min(CFG.mapHeight-1,cy+2);yy++)for(let xx=Math.max(0,cx-2);xx<=Math.min(CFG.width-1,cx+2);xx++){const q=a[yy*CFG.width+xx];if(q===MISSING)continue;sum+=Math.max(0,q);n++;max=Math.max(max,q)}if(!n)continue;const avg=(sum/n)*.72+max*.28;if(avg<45)continue;const c=colorDbz(avg/10),j=(y*sw+x)*4;sd[j]=c[0];sd[j+1]=c[1];sd[j+2]=c[2];sd[j+3]=c[3]}
  for(let i=0;i<a.length;i++){const q=a[i];if(q===MISSING||q<300)continue;const c=colorDbz(q/10),j=i*4;dd[j]=c[0];dd[j+1]=c[1];dd[j+2]=c[2];dd[j+3]=Math.round(c[3]*.46)}sx.putImageData(si,0,0);dx.putImageData(di,0,0);const out={soft,detail};broadcastRadarCache.set(key,out);while(broadcastRadarCache.size>24)broadcastRadarCache.delete(broadcastRadarCache.keys().next().value);return out;
}
function broadcastDrawRadarSurface(s,alpha){if(!s||alpha<=0)return;ctx.save();ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.globalCompositeOperation='screen';ctx.globalAlpha=alpha*.18;ctx.filter='blur(2.4px) saturate(1.18)';ctx.drawImage(s.soft,0,0,CFG.width,CFG.mapHeight);ctx.globalCompositeOperation='source-over';ctx.globalAlpha=alpha*.98;ctx.filter='saturate(1.10) contrast(1.03)';ctx.drawImage(s.soft,0,0,CFG.width,CFG.mapHeight);ctx.globalAlpha=alpha;ctx.filter='none';ctx.drawImage(s.detail,0,0);ctx.restore()}
function broadcastRadar(now=performance.now()){if(!state.frames.length)return;const tr=state.transition;if(tr&&tr.from!==tr.to){const u=clamp((now-tr.start)/CFG.radarBlendMs,0,1),e=u*u*(3-2*u);broadcastDrawRadarSurface(broadcastRadarSurfaces(state.frames[tr.from]),1-e);broadcastDrawRadarSurface(broadcastRadarSurfaces(state.frames[tr.to]),e);if(u>=1)state.transition=null}else broadcastDrawRadarSurface(broadcastRadarSurfaces(displayedFrame()),1)}

function broadcastCloudKey(){const a=surfaceFeatures();return`${view().id}|${a.length}|${a.map(f=>f?.properties?.timeobs||'').join('|')}`}
function broadcastAvgWind(){let x=0,y=0,n=0;for(const f of surfaceFeatures()){const p=f.properties||{},spd=Number(p.windspeed),dir=Number(p.winddir);if(!Number.isFinite(spd)||!Number.isFinite(dir)||spd<1)continue;const toward=(dir+180)*Math.PI/180;x+=Math.sin(toward)*spd;y+=-Math.cos(toward)*spd;n++}if(!n)return{x:0,y:0};const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m}}
function broadcastCloudCanvas(){const key=broadcastCloudKey();if(broadcastCloudCache.has(key))return broadcastCloudCache.get(key);const c=document.createElement('canvas');c.width=CFG.width;c.height=CFG.mapHeight;const x=c.getContext('2d'),samples=[];for(const f of surfaceFeatures()){const co=f.geometry?.coordinates,frac=cloudFraction(f.properties?.cloudcover);if(!co||frac==null)continue;const p=mapXY(co[1],co[0]);samples.push({x:p.x,y:p.y,f:frac})}if(!samples.length)return null;const step=5;x.save();x.filter='blur(2.2px)';for(let py=-step;py<CFG.mapHeight+step;py+=step)for(let px=-step;px<CFG.width+step;px+=step){let sw=0,sf=0;for(const s of samples){const d2=(s.x-px)**2+(s.y-py)**2,w=1/(700+d2);sw+=w;sf+=s.f*w}const f=sw?sf/sw:0,n=.48+.20*Math.sin(px*.053+py*.017)+.18*Math.sin(px*.019-py*.061)+.10*Math.sin((px+py)*.11),a=clamp((f-.10)*.14*(.62+n),0,.105);if(a<.006)continue;const shade=Math.round(190+42*n);x.fillStyle=`rgba(${shade},${shade+3},${shade+6},${a})`;x.fillRect(px,py,step+2,step+2)}x.restore();broadcastCloudCache.set(key,c);while(broadcastCloudCache.size>8)broadcastCloudCache.delete(broadcastCloudCache.keys().next().value);return c}
function broadcastAtmosphere(now=performance.now()){const c=broadcastCloudCanvas();if(!c)return;const w=broadcastAvgWind(),d=Math.sin(now/11000)*3;ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=.82;ctx.drawImage(c,w.x*d,w.y*d);ctx.restore()}

function broadcastCells(frame=displayedFrame()){if(!frame)return[];const key=`${frame.key}|${view().id}|broadcast6`;if(broadcastCellCache.has(key))return broadcastCellCache.get(key);const a=frame.views[view().id],cand=[],step=view().id==='home'?5:7;for(let y=7;y<CFG.mapHeight-7;y+=step)for(let x=7;x<CFG.width-7;x+=step){const q=a[y*CFG.width+x];if(q===MISSING||q<430)continue;let mx=q;for(let yy=y-4;yy<=y+4;yy+=2)for(let xx=x-4;xx<=x+4;xx+=2){const z=a[yy*CFG.width+xx];if(z!==MISSING)mx=Math.max(mx,z)}if(q<mx)continue;cand.push({x,y,dbz:q/10})}cand.sort((a,b)=>b.dbz-a.dbz);const sep=view().id==='home'?58:view().id==='metro'?52:view().id==='florida'?48:42,out=[];for(const c of cand){if(out.some(o=>(o.x-c.x)**2+(o.y-c.y)**2<sep*sep))continue;out.push(c);if(out.length>=3)break}broadcastCellCache.set(key,out);while(broadcastCellCache.size>24)broadcastCellCache.delete(broadcastCellCache.keys().next().value);return out}
function broadcastTag(x,y,text,accent='#fff',align='left'){ctx.save();ctx.font='800 6px Arial,Helvetica,sans-serif';const tw=ctx.measureText(text).width,w=tw+10,h=12;let bx=align==='right'?x-w:x;bx=clamp(bx,4,CFG.width-w-4);const by=clamp(y-h/2,27,CFG.height-h-25);ctx.fillStyle='rgba(2,8,12,.86)';ctx.strokeStyle=accent;ctx.lineWidth=.7;ctx.beginPath();ctx.roundRect(bx,by,w,h,3);ctx.fill();ctx.stroke();ctx.fillStyle='#f5fbfd';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(text,bx+5,by+h/2+.2);ctx.restore()}
function broadcastCellLabels(){for(const c of broadcastCells()){const accent=c.dbz>=55?'#ff53ba':c.dbz>=50?'#ff5c48':'#ffd84a';ctx.save();ctx.strokeStyle=accent;ctx.lineWidth=1.05;ctx.beginPath();ctx.arc(c.x,c.y,3.8,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(c.x+4.5,c.y-2);ctx.lineTo(c.x+9,c.y-6);ctx.stroke();ctx.restore();broadcastTag(c.x+9,c.y-8,`${Math.round(c.dbz)} dBZ`,accent)}}
function broadcastSevere(now=performance.now()){for(const p of fieldPeaks(state.severe.lightning,'broadcast-ltg',45,2)){const pulse=.65+.35*Math.sin(now/170+p.x*.1);ctx.save();ctx.strokeStyle=`rgba(120,231,255,${pulse})`;ctx.shadowColor='#60ddff';ctx.shadowBlur=5;ctx.lineWidth=1.15;ctx.beginPath();ctx.moveTo(p.x+1,p.y-6);ctx.lineTo(p.x-2,p.y);ctx.lineTo(p.x+1,p.y);ctx.lineTo(p.x-1,p.y+6);ctx.stroke();ctx.restore();broadcastTag(p.x+5,p.y+9,`LTG ${Math.round(p.value)}%`,'#69ddff')}for(const p of fieldPeaks(state.severe.mesh,'broadcast-mesh',25.4,2)){ctx.save();ctx.strokeStyle='#ff5acc';ctx.lineWidth=1.2;ctx.setLineDash([2,1]);ctx.beginPath();ctx.arc(p.x,p.y,p.value>=50.8?6:4.5,0,Math.PI*2);ctx.stroke();ctx.restore();broadcastTag(p.x+5,p.y-9,`${(p.value/25.4).toFixed(1)}in HAIL`,'#ff5acc')}}
function broadcastLabels(){ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=view().id==='home'?'700 7px Arial,Helvetica,sans-serif':'700 6.5px Arial,Helvetica,sans-serif';for(const[name,lat,lon]of view().labels){if(!within(lat,lon))continue;const p=mapXY(lat,lon);if(p.y<26||p.y>233)continue;ctx.lineWidth=3;ctx.strokeStyle='rgba(0,0,0,.94)';ctx.fillStyle='rgba(241,247,249,.90)';ctx.strokeText(name,p.x,p.y);ctx.fillText(name,p.x,p.y)}if(within(CFG.home.lat,CFG.home.lon)){const h=mapXY(CFG.home.lat,CFG.home.lon);ctx.strokeStyle='#fff';ctx.fillStyle='#4bd9ff';ctx.shadowColor='rgba(75,217,255,.82)';ctx.shadowBlur=5;ctx.lineWidth=1.15;ctx.beginPath();ctx.arc(h.x,h.y,5.3,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(h.x,h.y,2.1,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(75,217,255,.72)';ctx.beginPath();ctx.moveTo(h.x-8,h.y);ctx.lineTo(h.x-4,h.y);ctx.moveTo(h.x+4,h.y);ctx.lineTo(h.x+8,h.y);ctx.moveTo(h.x,h.y-8);ctx.lineTo(h.x,h.y-4);ctx.moveTo(h.x,h.y+4);ctx.lineTo(h.x,h.y+8);ctx.stroke()}ctx.restore()}
function broadcastScale(){const def=view(),lat=(def.bbox[1]+def.bbox[3])/2,widthMiles=(def.bbox[2]-def.bbox[0])*69*Math.cos(lat*Math.PI/180),px=clamp(def.scaleMi/widthMiles*CFG.width,27,76),x=CFG.width-10-px,y=226;ctx.save();ctx.strokeStyle='rgba(237,245,248,.65)';ctx.fillStyle='rgba(237,245,248,.68)';ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+px,y);ctx.moveTo(x,y-2.5);ctx.lineTo(x,y+2.5);ctx.moveTo(x+px,y-2.5);ctx.lineTo(x+px,y+2.5);ctx.stroke();ctx.font='700 5px Arial,Helvetica,sans-serif';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.fillText(`${def.scaleMi} MI`,x+px/2,y-2);ctx.restore()}
function broadcastHeadline(){const a=localAlert();if(a)return`HOME ${warningCode(a)} WARNING`;if(state.home.status!=='DRY')return`RAIN AT HOME ${Math.round(state.home.dbz||0)} dBZ`;const n=state.home.nearest,e=state.home.eta;if(n)return`HOME DRY · RAIN ${Math.max(1,Math.round(n.miles))} MI ${n.dir}${e?` · ETA ${e.minutes} MIN`:''}`;return'HOME DRY · NO NEARBY RAIN'}
function broadcastHeader(){const latest=state.frames.at(-1),fresh=freshness(),w=state.weather,a=localAlert(),now=new Date(),g=ctx.createLinearGradient(0,0,0,28);g.addColorStop(0,'rgba(2,10,15,.94)');g.addColorStop(.68,'rgba(2,10,15,.79)');g.addColorStop(1,'rgba(2,10,15,0)');ctx.fillStyle=g;ctx.fillRect(0,0,CFG.width,28);ctx.fillStyle='#24a9d7';ctx.fillRect(0,0,3,23);ctx.textBaseline='middle';ctx.textAlign='left';ctx.fillStyle='#f0f7f9';ctx.font='800 9px Arial,Helvetica,sans-serif';ctx.fillText('LIVE RADAR',9,8);ctx.fillStyle='#7fdfff';ctx.font='800 5.7px Arial,Helvetica,sans-serif';ctx.fillText(view().name,9,18);ctx.fillStyle=a?'#ffe44b':'#8aa6b1';ctx.font='700 5.2px Arial,Helvetica,sans-serif';ctx.fillText(a?`${warningCode(a)} WARNING AT HOME`:'MRMS · NWS WARNINGS · LTG · HAIL',84,18);ctx.beginPath();ctx.fillStyle=fresh==='live'?'#45ee8e':fresh==='delayed'?'#ffc84a':'#ff615d';ctx.arc(245,7.5,2.1,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d4e3e8';ctx.font='800 5.2px Arial,Helvetica,sans-serif';ctx.fillText(fresh.toUpperCase(),251,7.5);ctx.fillStyle='#839ba6';ctx.font='700 4.9px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';const age=Number.isFinite(ageMs())?Math.max(0,Math.round(ageMs()/60000)):'--';ctx.fillText(latest?`${utcTime(latest.time)} · ${age}m`:'ACQUIRING',239,18);ctx.textAlign='right';ctx.fillStyle='#f6fbfc';ctx.font='500 14px Arial,Helvetica,sans-serif';ctx.fillText(w?.temp!=null?`${w.temp}°`:'--°',371,9);ctx.font='700 5px Arial,Helvetica,sans-serif';ctx.fillStyle='#a7bac2';ctx.fillText(`${w?.windDir||'--'} ${w?.windMph??'--'} MPH`,405,17.5);ctx.fillStyle='#f1f7f9';ctx.font='700 8px Arial,Helvetica,sans-serif';ctx.fillText(now.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),450,8.5)}
function broadcastFooter(){const y=235,shown=displayedFrame(),ss=surfaceStats(),lm=fieldMax(state.severe.lightning),mm=fieldMax(state.severe.mesh),g=ctx.createLinearGradient(0,y,0,CFG.height);g.addColorStop(0,'rgba(2,9,13,.14)');g.addColorStop(.28,'rgba(2,9,13,.78)');g.addColorStop(1,'rgba(2,8,12,.94)');ctx.fillStyle=g;ctx.fillRect(0,y,CFG.width,22);ctx.strokeStyle='rgba(125,174,193,.20)';ctx.beginPath();ctx.moveTo(0,y+.5);ctx.lineTo(CFG.width,y+.5);ctx.stroke();ctx.textBaseline='middle';ctx.textAlign='left';ctx.font='800 6px Arial,Helvetica,sans-serif';ctx.fillStyle=localAlert()?'#ffe34d':state.home.status==='DRY'?'#9adfff':state.home.status==='LIGHT'?'#79ef9d':state.home.status==='RAIN'?'#ffe25e':'#ff8162';ctx.fillText(broadcastHeadline(),7,244);const lx=178,lw=92,ly=247,vals=[8,22,35,50,65];for(let i=0;i<5;i++){const c=colorDbz(vals[i]);ctx.fillStyle=`rgb(${c[0]},${c[1]},${c[2]})`;ctx.fillRect(lx+i*lw/5,ly,Math.ceil(lw/5),4)}ctx.fillStyle='#8ba1aa';ctx.font='700 4.6px Arial,Helvetica,sans-serif';ctx.fillText('RAIN',lx,241);ctx.textAlign='right';ctx.fillText('EXTREME',lx+lw,241);ctx.textAlign='left';ctx.fillText('dBZ',lx+lw+4,249);const tx=291,tw=54,ty=249,frames=state.frames,den=Math.max(1,frames.length-1);ctx.strokeStyle='rgba(138,170,183,.42)';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(tx+tw,ty);ctx.stroke();for(let i=0;i<frames.length;i++){const px=tx+i/den*tw;ctx.fillStyle=i===state.cursor?'#fff':'#607986';ctx.beginPath();ctx.arc(px,ty,i===state.cursor?1.9:1.1,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#8ba1aa';ctx.font='700 4.6px Arial,Helvetica,sans-serif';ctx.fillText('LOOP',tx,241);ctx.textAlign='right';ctx.fillText(shown?compactTime(shown.time):'--:--',tx+tw,241);const bits=[];if(lm!=null&&lm>=10)bits.push(`LTG ${Math.round(lm)}%`);if(mm!=null&&mm>=12.7)bits.push(`HAIL ${(mm/25.4).toFixed(1)}in`);if(!bits.length&&ss.cloud!=null)bits.push(`CLOUD ${Math.round(ss.cloud*100)}%`);ctx.textAlign='right';ctx.font='800 5.5px Arial,Helvetica,sans-serif';ctx.fillStyle=bits.length?'#e1edf1':'#8097a1';ctx.fillText(bits.join(' · '),449,244);ctx.font='700 4.7px Arial,Helvetica,sans-serif';ctx.fillStyle='#7e959f';ctx.fillText('LIVE NOAA',449,253)}
function broadcastVignette(){const g=ctx.createRadialGradient(CFG.width/2,CFG.height/2,CFG.height*.28,CFG.width/2,CFG.height/2,CFG.width*.72);g.addColorStop(.58,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.24)');ctx.fillStyle=g;ctx.fillRect(0,0,CFG.width,CFG.height)}

render=function(now=performance.now()){
  ctx.fillStyle='#02070b';ctx.fillRect(0,0,CFG.width,CFG.height);
  if(state.frames.length){broadcastBase();broadcastAtmosphere(now);broadcastRadar(now);drawTropics();drawWarnings();broadcastSevere(now);broadcastCellLabels();drawMotion();broadcastLabels();broadcastScale();broadcastVignette()}else renderUnavailable();
  broadcastHeader();broadcastFooter();
};
