function eHeader(){
  const w=state.weather||{},latest=state.frames.at(-1)?.time,age=Number.isFinite(ageMs())?Math.max(0,Math.round(ageMs()/60000)):null,cl=w.cloudCover!=null?Math.round(w.cloudCover*100):null,pop=Number.isFinite(w.forecast?.pop)?Math.round(w.forecast.pop):null,local=localAlert(),fresh=freshness();
  const g=ctx.createLinearGradient(0,0,0,E_MAP_TOP);g.addColorStop(0,'rgba(3,9,13,.98)');g.addColorStop(.78,'rgba(3,10,14,.92)');g.addColorStop(1,'rgba(3,10,14,.72)');ctx.fillStyle=g;ctx.fillRect(0,0,CFG.width,E_MAP_TOP);ctx.fillStyle='#31b8de';ctx.fillRect(0,0,3,E_MAP_TOP);
  ctx.textBaseline='middle';ctx.textAlign='left';ctx.fillStyle='#f1f6f8';ctx.font='900 9.2px Arial,Helvetica,sans-serif';ctx.fillText('RDR',9,8.2);ctx.fillStyle='#7ed9f4';ctx.font='800 5.8px Arial,Helvetica,sans-serif';ctx.fillText(view().name,9,19.6);
  ctx.fillStyle='#9fb2bb';ctx.font='700 4.6px Arial,Helvetica,sans-serif';ctx.fillText('MRMS REFLECTIVITY',65,8.3);ctx.fillStyle=fresh==='live'?'#53e895':fresh==='delayed'?'#f0c756':'#f06a62';ctx.beginPath();ctx.arc(67,19.4,1.6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#c8d5da';ctx.font='800 4.8px Arial,Helvetica,sans-serif';ctx.fillText(`${fresh.toUpperCase()}${latest?`  ${utcTime(latest)}${age!=null?`  ${age}m`:''}`:''}`,72,19.4);
  if(local){ctx.fillStyle=eHazardColor(warningCode(local));ctx.font='900 5.2px Arial,Helvetica,sans-serif';ctx.textAlign='center';ctx.fillText(`${warningCode(local)} WARNING AT HOME`,252,19.4)}
  ctx.textAlign='right';ctx.fillStyle='#f5f8f9';ctx.font='500 14.5px Arial,Helvetica,sans-serif';ctx.fillText(w.temp!=null?`${w.temp}°`:'--°',374,9.3);ctx.fillStyle='#dfe7ea';ctx.font='800 7.6px Arial,Helvetica,sans-serif';ctx.fillText(new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),451,9.2);ctx.fillStyle='#98adb6';ctx.font='700 4.7px Arial,Helvetica,sans-serif';const wx=[w.windDir&&w.windMph!=null?`${w.windDir} ${w.windMph} MPH`:null,w.rh!=null?`RH ${w.rh}%`:null,pop!=null?`NEXT HR ${pop}%`:cl!=null?`CLOUD ${cl}%`:null].filter(Boolean).join('  •  ');ctx.fillText(eFitText(wx||'CURRENT CONDITIONS',174,'700 4.7px Arial,Helvetica,sans-serif'),451,20);
  ctx.strokeStyle='rgba(119,151,164,.28)';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(0,E_MAP_TOP-.5);ctx.lineTo(CFG.width,E_MAP_TOP-.5);ctx.stroke();
}
function eHomeText(){const h=state.home,n=h.nearest,e=h.eta;if(h.status!=='DRY'){const dbz=Number.isFinite(h.dbz)?` ${Math.round(h.dbz)} dBZ`:'';return{main:h.status,sub:`AT HOME${dbz}`}}if(n)return{main:'DRY',sub:`RAIN ${Math.max(1,Math.round(n.miles))} MI ${n.dir}${e?`  •  ETA ${e.minutes}m`:''}`};return{main:'DRY',sub:'NO RAIN NEAR HOME'}}
function eHazardText(){const warnings=eWarningsInView().filter(x=>['TOR','SVR','FFW'].includes(x.code)),ltg=eFieldMax(state.severe.lightning),mesh=eFieldMax(state.severe.mesh),tropical=view().id==='regional'&&state.tropics.length;let main='NONE',sub='NO ACTIVE THREATS',accent='#8da4ad';if(warnings.length){const priority=['TOR','SVR','FFW'].find(c=>warnings.some(w=>w.code===c));main=`${priority} ${warnings.filter(w=>w.code===priority).length}`;sub='NWS WARNING IN VIEW';accent=eHazardColor(priority)}else if(ltg!=null&&ltg>=60){main=`LTG ${Math.round(ltg)}%`;sub=mesh!=null&&mesh>=25.4?`HAIL ${(mesh/25.4).toFixed(1)}\"`:'IN VIEW, NEXT 30 MIN';accent='#72dcf6'}else if(mesh!=null&&mesh>=25.4){main=`HAIL ${(mesh/25.4).toFixed(1)}\"`;sub='MRMS MESH IN VIEW';accent='#ff84d7'}else if(tropical){main='TROPICS';sub='NHC FEATURES ACTIVE';accent='#ffd160'}return{main,sub,accent}}
function eFooter(){
  ctx.fillStyle='rgba(3,9,13,.96)';ctx.fillRect(0,E_FOOT_TOP,CFG.width,CFG.height-E_FOOT_TOP);ctx.strokeStyle='rgba(123,154,166,.30)';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(0,E_FOOT_TOP+.5);ctx.lineTo(CFG.width,E_FOOT_TOP+.5);ctx.stroke();
  const a=eHomeText(),hz=eHazardText();ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillStyle='#76909b';ctx.font='800 4.5px Arial,Helvetica,sans-serif';ctx.fillText('HOME IMPACT',8,226);ctx.fillStyle=a.main==='DRY'?'#7fdcf7':a.main==='LIGHT'?'#78e59a':a.main==='RAIN'?'#ffe05b':a.main==='HEAVY'?'#ff8b52':'#ff5e74';ctx.font='900 8.4px Arial,Helvetica,sans-serif';ctx.fillText(a.main,8,237);ctx.fillStyle='#c0cdd2';ctx.font='700 4.7px Arial,Helvetica,sans-serif';ctx.fillText(eFitText(a.sub,142,'700 4.7px Arial,Helvetica,sans-serif'),8,248.5);
  ctx.strokeStyle='rgba(121,151,163,.20)';ctx.beginPath();ctx.moveTo(156,224);ctx.lineTo(156,253);ctx.moveTo(333,224);ctx.lineTo(333,253);ctx.stroke();ctx.fillStyle='#76909b';ctx.font='800 4.5px Arial,Helvetica,sans-serif';ctx.fillText('RADAR LOOP',165,226);const frames=state.frames,shown=displayedFrame(),x0=222,y=226;ctx.fillStyle='rgba(134,158,168,.35)';ctx.fillRect(x0,y-.7,90,1.4);for(let i=0;i<frames.length;i++){const x=x0+(frames.length===1?45:i/(frames.length-1)*90),sel=shown&&frames[i].key===shown.key;ctx.beginPath();ctx.fillStyle=sel?'#eaf7fb':'#617b86';ctx.arc(x,y,sel?2:1.25,0,Math.PI*2);ctx.fill()}ctx.textAlign='right';ctx.fillStyle='#b5c5cb';ctx.font='700 4.4px Arial,Helvetica,sans-serif';ctx.fillText(shown?utcTime(shown.time):'--:--Z',326,226);
  const lx=166,ly=235,lw=116,vals=[8,18,28,38,48,58,68];for(let i=0;i<vals.length;i++){const c=eRadarColor(vals[i]);ctx.fillStyle=`rgb(${c[0]|0},${c[1]|0},${c[2]|0})`;ctx.fillRect(lx+i*lw/vals.length,ly,Math.ceil(lw/vals.length),4)}ctx.textAlign='left';ctx.fillStyle='#a9bac1';ctx.font='700 4.3px Arial,Helvetica,sans-serif';ctx.fillText('LIGHT',166,246.5);ctx.textAlign='center';ctx.fillText('RAIN',224,246.5);ctx.textAlign='right';ctx.fillText('INTENSE',282,246.5);ctx.textAlign='left';ctx.fillText('dBZ',287,237.5);ctx.textAlign='left';ctx.fillStyle='#76909b';ctx.font='800 4.5px Arial,Helvetica,sans-serif';ctx.fillText('HAZARDS',342,226);ctx.fillStyle=hz.accent;ctx.font='900 7.8px Arial,Helvetica,sans-serif';ctx.fillText(hz.main,342,237);ctx.fillStyle='#aebfc5';ctx.font='700 4.5px Arial,Helvetica,sans-serif';ctx.fillText(eFitText(hz.sub,105,'700 4.5px Arial,Helvetica,sans-serif'),342,248.5);
}
function eVignette(){const g=ctx.createRadialGradient(CFG.width*.52,CFG.height*.48,CFG.height*.28,CFG.width*.52,CFG.height*.48,CFG.width*.72);g.addColorStop(.55,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.16)');ctx.fillStyle=g;ctx.fillRect(0,E_MAP_TOP,CFG.width,E_MAP_BOTTOM-E_MAP_TOP)}
function ePerf(ms){if(!state.perf)state.perf={samples:[],last:null};state.perf.last=ms;state.perf.samples.push(ms);if(state.perf.samples.length>180)state.perf.samples.shift()}
function eWarmCurrentView(){const t=performance.now();eBase();eLines();for(const f of state.frames)eRadarCanvas(f);eCells();if(state.severe.lightning)ePeak(state.severe.lightning,view(),70,3);if(state.severe.mesh)ePeak(state.severe.mesh,view(),25.4,2);return performance.now()-t}
render=function(now=performance.now()){
  const t0=performance.now();ctx.fillStyle='#04131b';ctx.fillRect(0,0,CFG.width,CFG.height);
  if(panel.dataset.ready!=='true'){ePerf(performance.now()-t0);return}
  if(state.frames.length){ctx.drawImage(eBase(),0,0);eRadar(now);ctx.drawImage(eLines(),0,0);eDrawTropics();eDrawWarnings();eNearestRain();const occ=eOcc();eSevereSymbols(occ);eStormFocus(occ);eWarningLabels(occ);eCityLabels(occ);eHomeMarker();eScale();eVignette()}else renderUnavailable();eHeader();eFooter();ePerf(performance.now()-t0);
};
